config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  get 'projects' => 'index#projects'

  get 'experience' => 'index#experience'

  get 'contact' => 'index#contact'

  get 'about' => 'index#about'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def projects
  end

  def experience
  end

  def contact
  end

  def about
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
def youtube_video(url)
    render :partial => 'index/video', :locals => { :url => "https://www.youtube.com/watch?v=Q4B4C-4tkYo" }
  end 

end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/about.html.erb
	<%=image_tag("about.png")%>
		
	<%=image_tag("me.png")%>

<div class="name_panel">
	
	<div class="row padding">
		<div class="col-md-4">
			
			<%=image_tag("florida.png")%>
			<p class="textcenter padding">Born in South Florida where I was spoiled with sunshine and salt water throughout my childhood, I've always enjoyed anything and everything that gets me outside. During that time, I had a habit of finding little projects for myself and family furniture that needed my artistic touch (others disagreed). I like to think that was the creative side deciding to take over.</p>
		</div>
		<div class="col-md-4">
			<%=image_tag("alabama.png")%>
			<p class="textcenter padding">My four years of college were spent at Auburn University. Vastly different and much smaller than my hometown, Auburn still managed to provide perspective and experiences I could've never expected. It was my junior year when I was introduced to HTML, and it was the first time work felt like fun.</p>
		</div>
		<div class="col-md-4">
			<%=image_tag("georgia.png")%>
			<p class="textcenter padding">I made the move to Atlanta upon receiving an internship at a hospitality PR agency and then a healthcare agency. At some point, I realized I wanted to be on the other side of the table. Days were spent learning about revolutionary ideas people were bringing to life, and I was eager to join the side of creation. Remembering how much I enjoyed coding and design, I began to explore my options and couldn't be happier with my decision.</p>
		</div>
	</div>
</div>
	
	

app/views/index/contact.html.erb
<center>
<%= image_tag('contact.png')%>
</center>

app/views/index/experience.html.erb
<%= image_tag("experience.png")%>
<%=image_tag("education2.png")%>

<div class="name_panel">
	<div class= "row">
		<div class= "col-md-6">
			<%= image_tag('GA.png')%>
		</div>
		<div class= "col-md-6">
			<%= image_tag('TTS.png')%>
		</div>
	</div></br></br>
	
	
</div>

app/views/index/home.html.erb
<div>
	
	<div id="hero">
		<div id="name_logo">
			<%= image_tag('scname.png')%>
		</div>
		<%=image_tag("headshot2.png")%></br>
		<!-- <div class="resume-button container-fluid pull-right">
					<a href="https://drive.google.com/file/d/0B-TZYLQGy9cBRVp1cU5vNUlXOWs/view?usp=sharing" target="_blank"><button class="btn btn-primary">Resume</button></a>
		</div> -->
	</div>

<div class="name_panel">
	<div class="row home-row">
		<div class="col-md-6">
			<%=image_tag("uxicon.png")%></br>
			<p class="padding center"> I love making people happy.</br> When I first learned about UX, </br>I realized it was a way to combine that with my </br>passion for making things. The combination of creation,</br> tech and people UX brings makes it, in my opinion, </br>forever relevant.</p> 
		</div>
		<div class="col-md-6">
			<%=image_tag("devicon.png")%></br>
			<p class="padding center">Learning both design and development </br>was important to me. Other than selfish reasons</br> (I love both), I wanted to bridge the gap between</br> two important parts of a process to deliver </br>quality, meaningful products.</p>
		</div>
	</div>
	<div>
		<p class="padding center">*This website was built with Ruby on Rails with a little help from Bootstrap, Heroku and my tired fingers.</p>
	</div>
</div>
	


	
</div>

app/views/index/projects.html.erb
<%= image_tag('projects.png')%>
<%= image_tag('projects2.png')%>


<div class="name_panel">
  

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-warning">  
      <div class="row">
        <div class="col-md-9">
          <h4>Tapetrack Web App</h4>
        </div>
        <div class="col-md-3">
          <p></p>
         <button type="button" class="btn btn-warning"data-toggle="modal" data-target=".bs-example-modal-lg">+</button>
        </div>
      </div>
      <%= image_tag('tapetracksnap2.png')%>
    </div>
  </div>
<div class="col-md-4">
    <div class="panel panel-warning">
      <div class="row">
        <div class="col-md-9">
          <h4>CardFeed Mobile Design</h4>
        </div>
        <div class="col-md-3">
          <p></p>
         <button type="button" class="btn btn-warning"data-toggle="modal" data-target=".bs-example-modal-lg-3">+</button>
        </div>
      </div>
      <%= image_tag('cardfeed2.png')%>
    </div>
  </div>
   <!-- <div class="col-md-4">
    <div class="panel panel-warning">
      <div class="row">
        <div class="col-md-9">
          <h4>IHG Mobile App Design</h4>
        </div>
        <div class="col-md-3">
          <p></p>
         <button type="button" class="btn btn-warning"data-toggle="modal" data-target=".bs-example-modal-lg-2">+</button>
        </div>
      </div>
      <%= image_tag('IHG.png')%>
    </div>
  </div> -->
  

<!--   <div class="row">
    <div class="col-md-4">
    <div class="panel panel-warning">  
      <div class="panel-heading">
        Tapetrack Web App
      </div>   
      <%= image_tag('tapetracksnap2.png')%>
    </div>
    
  </div>
  <div class="col-md-3">
    <div class="panel panel-warning">
      <div class="panel-heading">
        Williams-Sonoma Microsite Design
      </div>
      <%= image_tag('WS.png')%>
    </div>
    
  </div>
  <div class="col-md-4">
  </div>
  </div> -->

</div>



<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
          <div class="row">
            <div class="col-md-6">
              <%=image_tag("tapetracktitle.png")%>
              <p class="padding">My first web application, Tapetrack was inspired by an idea I held on to for a while and finally built the skills to create. The idea is an application allowing users to create mixtapes for others in the digital space and elicit as many 90's flashbacks as possible. I plan to keep playing with and adding to this project for fun and to continue building my skills. </p></br>
              <div class="row">
                <div class="col-md-6">
                  <p class="padding"><%= image_tag("tools.png")%></p>
                    <ul>
                      <li>Ruby on Rails</li>
                      <li>Bootstrap</li>
                    </ul>
                </div>
                <div class="col-md-6">
                  <a href="https://youtu.be/Q4B4C-4tkYo" target="_blank"><button class="btn btn-tt">App Demo</button></a>
                </div>
              </div>


            </div>
            <div class="col-md-6">
              <p></p>
              </br>
             <%= image_tag('tapetrackss.png')%>

             </div>
          </div>
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-lg-2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      hi
    </div>
  </div>
</div>

<div class="modal fade bs-example-modal-lg-3" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="row">
        <div class="col-md-6">
          <p></p>
          <%=image_tag("cardfeed3.png")%></br>
          <p class="padding">An independent project, CardFeed began as an idea designed and tailored to a single classmate's interests and needs. After an initial interview, the idea took shape as a news and content curator based on the user's interests. I later revisited the idea to expand user testing to others and elaborate on the first iteration. After four rounds of user testing and three primary iterations, CardFeed's final prototype features the ability to filter content by audio, text and video and move through the app with simple swipe motions.</p>

          <div class="row">
            <div class="col-md-6">
              <h3 class="cfblue">Product Goals</h3>
                <ul>
                  <li>Easily consume and share content.</li>
                  <li>Like or dislike content, tailoring future feed results.</li>
                  <li> Simple swipe motions allowing quick consumption, sharing and saving.</li>
                </p>
            </div>
            <div class="col-md-6">
              <h3 class="cfblue">Design Tools</h3>
              <p class="center">Sketch, Axure</p>
              </br>

              <!-- <button class="btn btn-cf">Prototype Demo</button> -->
            </div>
          </div>

        </div>
        <div class="col-md-6">
          <p></p>
          <%=image_tag("cardfeed.png")%>
        </div>
      </div></br>

      <h3 class="cfblue">Process</h3></br>
      
      <div class="row padding">
        <div class="col-md-4">
          <%=image_tag("interview.png")%>
          <h4 class=>User Interview</h4>
          <p>The initial user interview pinpointed areas the user felt he could be served more efficiently. Together we decided a path for my design to pursue.</p>
        </div>
        <div class="col-md-3">
          <%=image_tag("sketching.png")%>
          <h4>Sketch</h4>
          <p>After sketching out simple designs to demonstrate functionality, I met with the user to get feedback and then implemented suggestions to create the first prototype. </p>
        </div>
        <div class="col-md-5">
          <%=image_tag("usertests.png")%>
          <h4>Prototyping + Research</h4>
          <p>Using the first prototype, I expanded user testing by sketching out additional ideas and observing user preference and interaction beahvior. I repeated this step after the next three iterations to reach the final prototype.</p>
        </div>
      </div></br>

      <div class="row sketchimages">
        <div class="col-md-6">
          <p></p>
          <p></p>
          <%=image_tag("sketches.png")%>
        </div>
        <div class="col-md-6">
          <p></p>
          <p></p>          
          <%=image_tag("ken.jpg")%>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<center>
		<div class="top">
			<div class="row bar">
				<div class="col-md-2">
					<%= link_to image_tag("projecticon.png"), projects_path %>
					<h5>Projects</h5>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("experienceicon.png"), experience_path %>
					<h5>Education</h5>
				</div>
				<div class="col-md-4">
					<%= link_to image_tag("logo2.png"), root_path %>
				</div>
				<div class="col-md-2">
					<%= link_to image_tag("abouticon.png"), about_path %>
					<h5>About</h5>
				</div>
				<div class="col-md-2">
					<div class="row">
						<div class="col-md-12">
							<a href="mailto:stephjanecz@gmail.com" target="_blank"><%=image_tag('mail.png')%></a>

							<a href="https://www.linkedin.com/in/stephanieczajkowski" target="_blank"><%=image_tag('linkedin.png')%></a>
								
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							
							<a href="http://uxnfrecks.tumblr.com/" target="_blank"><%=image_tag('tumblr.png')%></a>
						
						
							<a href="https://github.com/stephjane" target="_blank"><%=image_tag('github.png')%></a>
						</div>
					</div>
				</div>
			</div>
		</div>
			
			
		</center>

		
		

		<center>
			<div class="container">
			<%= yield %>
			</div>
		</center>

		<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>

</body>

</html>